name: Build and Push

on:
  push:
    branches:
      - main
  
jobs:
  buildx:
    name: Build and Push the Docker Images
    
    strategy:
      matrix:
        include:
          - name: bitbucket
          - name: bamboo
          - name: jira
    
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-${{ matrix.name }}
          restore-keys: |
            artemis-${{ matrix.name }}
        
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/ls1intum/artemis-${{ matrix.name }}:latest
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
