name: Build and Push

on:
  push:
    #    branches:
    #- main
  workflow_dispatch: 
    # __Future improvement:__
    # Allow definition of versions as parameter of manual run. 
    # Input may look like this: 
    #    inputs:
    #      jira_version: 
    #        default:  8.20.6
    #        required: true
    #      bitbucket_version: 
    #        default: 7.21.0
    #        required: true
    #      bamboo_version:
    #        default: 8.1.3
    #        required: true

env: 
  JIRA_VERSION: 8.20.6
  BITBUCKET_VERSION: 7.21.0
  BAMBOO_VERSION: 8.1.3

jobs:
  buildx:
    name: Build and Push the Docker Images

    strategy:
      matrix:
        include:
          - name: bitbucket
            version: ${{ BITBUCKET_VERSION }}
          - name: bamboo
            version: ${{ BAMBOO_VERSION }}
          - name: jira
            version: ${{ JIRA_VERSION }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-${{ matrix.name }}
          restore-keys: |
            artemis-${{ matrix.name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: ${{ matrix.version }}
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/ls1intum/artemis-${{ matrix.name }}:latest,ghcr.io/ls1intum/artemis-${{ matrix.name }}:${{ matrix.version }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-bamboo-variants:
    name: Build and Push the Docker Images for the Bamboo variants
    runs-on: ubuntu-latest
    needs: [ buildx ]

    strategy:
      matrix:
        include:
          - name: c
            version: ${{ BAMBOO_VERSION }}
            platforms: linux/arm64/v8,linux/amd64
          - name: swift
            version: ${{ BAMBOO_VERSION }}
            platforms: linux/amd64

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-bamboo-${{ matrix.name }}
          restore-keys: |
            artemis-bamboo-${{ matrix.name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: ${{ matrix.version }}
          context: ./bamboo/${{ matrix.name }}
          file: ./bamboo/${{ matrix.name }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ghcr.io/ls1intum/artemis-bamboo:latest-${{ matrix.name }},ghcr.io/ls1intum/artemis-bamboo:${{ matrix.version }}-${{ matrix.name }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
